<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0</TargetFrameworks>
		<Configurations>Debug;Release;</Configurations>	
		<LangVersion>latest</LangVersion>
		<Product>Gizmo.DAL.Entities</Product>
		<Description>Gizmo.DAL.Entities</Description>
		<Copyright>Copyright ©  2014</Copyright>
		<Authors />
		<Company>NETProjects</Company>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Optimize>true</Optimize>		
		<!-- !IMPORTANT! will break compatibility with older builds if name is changed-->
		<AssemblyName>Gizmo.DAL.Entities</AssemblyName>

    <!-- !IMPORTANT! will break compatibility with migration generation, needs carefull consideration-->
    <Nullable>disable</Nullable>
    <Version>3.0.0</Version>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Release'">
		<Optimize>true</Optimize>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Debug'">
		<Optimize>false</Optimize>
		<DefineConstants>DEBUG;TRACE</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="protobuf-net" Version="2.4.6" />
	</ItemGroup>

	<ItemGroup Condition="Exists('..\Gizmo.Shared\Gizmo.Shared.csproj')">
	  <ProjectReference Include="..\Gizmo.Shared\Gizmo.Shared.csproj" />
	</ItemGroup>

	<ItemGroup Condition="!Exists('..\Gizmo.Shared\Gizmo.Shared.csproj')">
	  <PackageReference Include="Gizmo.Shared" Version="1.0.7" />
	</ItemGroup>

</Project>
